"""empty message

Revision ID: 8c6e1aa14499
Revises: 70495c03c2b8
Create Date: 2023-01-02 20:57:50.880138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6e1aa14499'
down_revision = '70495c03c2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Escursione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_escursione_template', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'EscursioneTemplate', ['id_escursione_template'], ['id_escursione_template'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Escursione', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_escursione_template')

    # ### end Alembic commands ###
