"""empty message

Revision ID: bb4660e4100e
Revises: 
Create Date: 2023-01-27 14:51:17.878293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4660e4100e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EscursioneTemplate',
    sa.Column('id_escursione_template', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('partenza', sa.String(length=30), nullable=True),
    sa.Column('mapLink', sa.String(length=2000), nullable=True),
    sa.Column('dislivello', sa.Integer(), nullable=True),
    sa.Column('distanza', sa.Float(), nullable=True),
    sa.Column('tempo_stimato', sa.String(length=20), nullable=True),
    sa.Column('altezza_min', sa.Integer(), nullable=True),
    sa.Column('altezza_max', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('strumenti_richiesti', sa.String(length=500), nullable=True),
    sa.Column('descrizione_percorso', sa.String(length=2000), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_escursione_template')
    )
    op.create_table('Utente',
    sa.Column('id_firebase', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('cognome', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('flag_organizzatore', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('data_di_nascita', sa.Date(), nullable=True),
    sa.Column('livello_camminatore', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_firebase')
    )
    op.create_table('Amici',
    sa.Column('id_firebase', sa.String(length=50), nullable=False),
    sa.Column('id_friend', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_firebase'], ['Utente.id_firebase'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_friend'], ['Utente.id_firebase'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_firebase', 'id_friend')
    )
    op.create_table('Escursione',
    sa.Column('id_escursione', sa.String(length=50), nullable=False),
    sa.Column('orario_ritrovo', sa.String(length=20), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('numero_max', sa.Integer(), nullable=True),
    sa.Column('id_escursione_template', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_escursione_template'], ['EscursioneTemplate.id_escursione_template'], ),
    sa.PrimaryKeyConstraint('id_escursione')
    )
    op.create_table('Organizza',
    sa.Column('id_organizzatore', sa.String(length=50), nullable=False),
    sa.Column('id_escursione', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_escursione'], ['Escursione.id_escursione'], ),
    sa.ForeignKeyConstraint(['id_organizzatore'], ['Utente.id_firebase'], ),
    sa.PrimaryKeyConstraint('id_organizzatore', 'id_escursione')
    )
    op.create_table('Utente_Escursione',
    sa.Column('id_firebase', sa.String(length=50), nullable=False),
    sa.Column('id_escursione', sa.String(length=50), nullable=False),
    sa.Column('stato', sa.Integer(), nullable=True),
    sa.Column('valutazione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_escursione'], ['Escursione.id_escursione'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_firebase'], ['Utente.id_firebase'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_firebase', 'id_escursione')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Utente_Escursione')
    op.drop_table('Organizza')
    op.drop_table('Escursione')
    op.drop_table('Amici')
    op.drop_table('Utente')
    op.drop_table('EscursioneTemplate')
    # ### end Alembic commands ###
